-- liquibase formatted sql

-- changeset sokol:1
CREATE TABLE users (
    id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL unique,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL
);